[14기 장호철] 주변시설 초기 세팅
wecode-bootcamp-korea/14-2nd-SHABANG-frontend pull request #3
Opened 2020-12-02 08:48 UTC by HocheolJang

## 수정 사항 간략한 한줄 요약
- 주변시설 카드 컴포넌트 (진행중)
- 카카오 MAP API 연동
- JSON형태로 데이터 불러옴 (useState)
		 
## 수정 사항들 자세한 내용
- 위와 동일

## 기타 질문 및 특이 사항
- useState와 useEffect를 꼭 사용해보고싶은데 이해도가 떨어지는 것같습니다 ㅜㅜ
정 안되면 Class형으로 다시 바꿔서 해보겠습니다... 그것도 어떻게 할 수 있을지 고민이기는 하지만...
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-02 13:24 UTC, joonsikyang reviewed
> useState와 useEffect를 꼭 사용해보고싶은데 이해도가 떨어지는 것같습니다 ㅜㅜ
정 안되면 Class형으로 다시 바꿔서 해보겠습니다... 그것도 어떻게 할 수 있을지 고민이기는 하지만...
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

- 맞습니다 호철님! 처음에 시간 걸려도 학습 해보시고 하나씩 적용해보세요. 2차 프로젝트틑 1차 프로젝트와 목표 자체가 다르다는 점 잊지 마시고 더욱 의미있게 본인걸로 가지고 가주세요! :) 리뷰 내용 확인 부탁드립니다!

2020-12-02 13:24 UTC, joonsikyang commented on src/Components/NearBy/test.js
> +// `;
push 하기 전에 이런 파일은 삭제해주세요!

2020-12-02 13:24 UTC, joonsikyang commented on public/index.html
> +
18번째, 22번째 줄 엔터 처리 삭제!

2020-12-02 13:24 UTC, joonsikyang commented on src/Components/NearBy/Component/Dimmer.js
> +    <div className="Dimmer" onClick={modalOff}></div>;
```suggestion
    <div className="Dimmer" onClick={modalOff} />
```
- 이런 기본적인 것들 검토하는 습관 기르시면 코드도 깔끔해지고 안 풀리던 문제도 해결되고 그렇습니다-!

2020-12-02 13:24 UTC, joonsikyang commented on src/Components/NearBy/Component/Nearby.js
> +  };
- async await에 대해서 간략하게 설명해주세요👐
- ㅋㅅㅅㅈ ^^

2020-12-02 13:24 UTC, joonsikyang commented on src/Components/NearBy/NearbyCard.js
> +`;
컴포넌트 사이 사이 한줄씩 띄워주세요!

2020-12-02 13:24 UTC, joonsikyang commented on src/Components/NearBy/NearbyCard.js
> +        </NearbyCardBody>
```suggestion
        {isHidden && (
          <NearbyCardBody>
            <p className="detailAddress">강남구 삼성동</p>
            <NearbyCardMapImg onClick={modalOn}>
              <span>지도 이미지 자리</span>
              <span className="showDetail">자세히 보기</span>
            </NearbyCardMapImg>
          </NearbyCardBody>
        )}
```

2020-12-02 13:24 UTC, joonsikyang commented on src/Components/NearBy/NearbyCard.js
> +      isHidden: "show",
무슨 모달이고, 뭐가 히든인지 명확한 키 이름 사용해주시면 좋겠네요! 2차 프로젝트인 만큼 기본적인 것들 더욱 충실히 해주세요

2020-12-02 15:00 UTC, HocheolJang commented on src/Components/NearBy/test.js
> +// `;
네 알겠습니다~
죄송합니다

2020-12-02 15:00 UTC, HocheolJang commented on public/index.html
> +
넴!

2020-12-02 15:00 UTC, HocheolJang commented on src/Components/NearBy/Component/Dimmer.js
> +    <div className="Dimmer" onClick={modalOff}></div>;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
네 알겠습니다... 셀프클로징!

2020-12-02 15:02 UTC, HocheolJang commented on src/Components/NearBy/Component/Nearby.js
> +  };
ㅋㅋㅋㅋㅋ
async와 await는 잘 모르는 것인데 카카오지도 API를 검색하고 쓰던중
검색해서 비슷한 형태로 쓰길래 따라 써봤습니다
현재까지 아는바로는 async를 통해서 비동기화 처리를 요청하는 것이고, await는 class형에서 .then으로 쓰던 것과 비슷한 역할을 한다고 알고있습니다.

ㅋㅅㅅㅈ하겠습니다

2020-12-02 15:02 UTC, HocheolJang commented on src/Components/NearBy/NearbyCard.js
> +`;
넵!

2020-12-02 15:03 UTC, HocheolJang commented on src/Components/NearBy/NearbyCard.js
> +        </NearbyCardBody>
오...넵 이런 문법으로 쓰겠습니다 ㅎㅎ

2020-12-02 15:03 UTC, HocheolJang commented on src/Components/NearBy/NearbyCard.js
> +      isHidden: "show",
알겠습니다!

2020-12-02 15:08 UTC, HocheolJang commented on public/index.html
> +
아 이거는 프리티어 기본 속성으로 떨어트리는 것같습니당...ㅎㅎㅎ

2020-12-07 06:38 UTC, HocheolJang commented
다시 컨플릭트 해결했습니다!

2020-12-07 07:37 UTC, Jun4928 requested changes
호철님 리뷰 확인 및 반영 해 주세요 🙌

2020-12-07 07:37 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +class NearbyCard extends Component {
호철님 해당 컴포넌트도 함수형으로 작성해 보세요 👍

2020-12-07 07:37 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +      isBodyShow: !this.state.isBodyShow,
두 변수가 동일한 역할을 하고 있네요
그렇다면, 두 개의 상태로 관리하기 보다 하나의 상태에 적절한 이름을 붙여주는게 좋지 않을까요?

아래 `render` 함수에서 `isArrowUp`, `isBodyShow` 두 변수 모두 조건부 렌더링을 위해서 사용되고 있습니다.

2020-12-07 07:37 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +  }
styled component 의 가장 큰 장점 중 하나는 
**JavaScript 변수**에 접근 가능하다는 것 입니다. 
styled component 도 **컴포넌트**  이기 때문에
props 로 값을 내려주고 받아서 사용할 수 있습니다.

ex)
```js
const CardHeader = styled.div`
...

.arrow {
    width: 15px;
    margin-right: 20px;
    transition: all ease 0.4s;
    transform: rotate(${props => props.isArrowUp ?  "-90" : "-270"}deg);
}
`
```

2020-12-07 07:37 UTC, Jun4928 commented on src/Components/NearBy/Modal/NearbyModal.js
> +  ];
해당 상수들 다음 리뷰를 참고해서 리팩토링 해 주세요

### 1. 상수 관련 변수명
- 상수는 변하지 않기 때문에 let 아닌 const 를 사용합니다.
- 변하지 않는 데이터를 저장하는 상수명은 대문자 SNAKE_CASE 로 짓는 것이 컨벤션 입니다.
- 변수명의 이름에 `data`, `list`, `info` 등의 의미없는 단어를 삭제 해 주세요. 
개발자는 변수에 데이터가 담긴다는 것을 이미 알고 있습니다.
- 배열은 `복수`로 변수명을 짓는것이 컨벤션 입니다. 

ex)
```js
const SUBWAYS  = [...]
const CAFES = [...]
const STORES = [...]
const SCHOOLS = [...]
```
### 2. 목데이터 파일로 분리하기
이렇게 상수가 긴 경우에 따로 파일로 빼서 관리하는 것이 좋습니다. 
해당 컴포넌트의 로직이 바로 보이지 않기 때문에 코드의 가독성을 방해 합니다. 

ex)
```js
import { SUBWAYS, CAFES, STORES, SCHOOLS } from 'nearByModalMocks'
```

2020-12-07 07:37 UTC, Jun4928 commented on src/Components/NearBy/Modal/NearbyModal.js
> +    createSchoolMarkers();
이렇게 반복되는 로직은 함수로 **추상화**를 시켜야 합니다.
어떤 배열의 데이터가 들어오더라도 같은 일을 하는 함수를 만들어야 합니다.

현재 반복되고 있는 로직을 살펴보겠습니다.
- 배열의 요소를 순회하며 Marker 를 만드는 함수가 각각의 변수마다 작성되어 있습니다.
- 만들어진 각각의 마커의 요소를 순회하며 setMap(map) 을 붙이는 로직이 각각 변수마다 작성되어 있습니다.
그렇다면, 함수를 하나 만들고, 들어가는 변수만 바꿔주면 되지 않을까요?
- 각각의 마커를 저장하는 배열도 필요없이 바로 데이터를 순회하며 마커를 만들고 setMap(map) 을 실행하면 되지 않을까요?
왜냐하면, 현재 변수를 선언해놓고 사용하고 있는 곳이 없습니다.

ex)
```js
const createAndSetMarkers = (items, type, map) => {
  items.forEach(({latitude, longtitude}) => {
    const imageSrc = `images/icon/${type}On.png`
    const imgageSize = new kakao.maps.Size(35, 35)
    const markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize)
    const marker = new kakao.maps.Marker({
      position: new kakao.maps.LatLng(latitude, longtitude),
      image: markerImage,
      clickable: true,
    })
    
    marker.setMap(map)
  })
}

createAndSetMarkers(subways, 'subway', map)
createAndSetMarkers(stores, 'store', map)
createAndSetMarkers(cafes, 'cafe', map)
createAndSetMarkers(schools, 'school', map)
```

1. 함수의 첫번째 인자는 items 로 marker 를 찍을 배열을 받습니다.
2. 두번째 인자는 배열 데이터의 타입입니다. imageSrc 를 template literal 로 처리하기 위함입니다.
3. map 객체를 인자로 받습니다.

2020-12-07 11:20 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +class NearbyCard extends Component {
네 ㅋㅋㅋ리팩토링하면서 한 번 바꿔보겠습니다

2020-12-07 11:21 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +      isBodyShow: !this.state.isBodyShow,
오 그렇게 되겠군요!
알겠습니다

2020-12-07 11:25 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +  }
음...이렇게 하니까 에러가 뜨긴하던데 ㅜㅜ 
한 번 찾아서 바꿔보겠습니다

2020-12-07 11:26 UTC, HocheolJang commented on src/Components/NearBy/Modal/NearbyModal.js
> +  ];
넵 ㅎㅎ이건 현재 분리해뒀습니다!
다 바꿔뒀습니당

2020-12-07 11:26 UTC, HocheolJang commented on src/Components/NearBy/Modal/NearbyModal.js
> +    createSchoolMarkers();
오...한번 찾아보고 해보겠습니다

2020-12-07 12:23 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +  }
어떤 에러가 떴나요?

2020-12-07 12:24 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +      isBodyShow: !this.state.isBodyShow,
css도 props 로 true 또는 false 값(상태값)을 내려주면 되지 않을까요?

2020-12-08 02:57 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +class NearbyCard extends Component {
바꿨습니다! 
최초에는 한 번 섞어서 써보려고 했긴했는데, 굳이 그렇게 할 필요가 없었겠네요 ㅎㅎ
함수형 계속 연습할겸 함수형으로 쓰겠습니다

2020-12-08 03:08 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +      isBodyShow: !this.state.isBodyShow,
props로 내리는 방법은 모르지만, 우선 합쳐서 진행했습니다.
조금 있다가 또 확인 부탁드립니다!

2020-12-08 03:18 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +  }
props로 내리는 방법 을 모르겠습니다 ㅜㅜ
말씀하신대로 css는 수정했는데 위에서 화살표 이미지 하나만 props로 내리는 방법을 모르겠습니당
조금만 더 찾아보겠스빈다!

2020-12-08 05:50 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +      isBodyShow: !this.state.isBodyShow,
[스타일드 컴포넌트](https://styled-components.com/docs/basics#adapting-based-on-props) 공식문서 참고 해 보시겠어요?

2020-12-08 05:53 UTC, Jun4928 commented on src/Components/NearBy/Card/NearbyCard.js
> +      isBodyShow: !this.state.isBodyShow,
[스택오버플로우 링크](https://stackoverflow.com/a/54493949/13788875)도 참고해 보세요!

2020-12-08 08:53 UTC, HocheolJang commented on src/Components/NearBy/Modal/NearbyModal.js
> +    createSchoolMarkers();
이렇게 바꿔보려는데 어렵네요 ㅜㅜㅜㅋㅋㅋㅋ

2020-12-08 10:43 UTC, Jun4928 commented on src/Components/NearBy/Modal/NearbyModal.js
> +    createSchoolMarkers();
도전! 연습하셔야 합니다 ㅎㅎ

2020-12-10 04:21 UTC, claire-euni reviewed
호철님 반복되는 함수와 리턴문 하나로 합칠수 있게 고민해보세요 🤗

2020-12-10 04:21 UTC, claire-euni commented on src/Components/NearBy/Card/NearbyCard.js
> +            // className={isBodyShow ? "arrowUp" : "arrowDown"} 이걸 어떻게 props로 내려줄 수 있을까여?
isBodyShow의 상태를 스타일 컴포넌트에 props로 전달하고 싶다는 말씀인가요? 
일단 스타일 컴포넌트로 Img 태그를 변환시키고 전달하고자 하는 props를 `isBodyShow={isBodyShow}` 이렇게 전달해줘야합니다. 
제가 적용해보니 잘 되네요. 한번 해보세요 호철님~

```js
 <Arrow
            isBodyShow={isBodyShow}
            alt="클릭하면 내용을 볼 수 있어요"
            src="images/icon/arrow2.png"  />
```


```css
const Arrow = styled.img`
  width: 15px;
  margin-right: 20px;
  transition: transform ease 0.4s;
  transform: ${({ isBodyShow }) =>
    isBodyShow ? "rotate(-270deg)" : "rotate(-90deg)"};
`;

```

2020-12-10 04:21 UTC, claire-euni commented on src/Components/NearBy/Modal/Component/NearbyModalFooter.js
> +          <span>지하철</span>
비슷한 구문이 반복되고 있습니다.
아래와 같이 반복되는 틀을 만들어두고 데이터와 함수만 차이있게 넣어줄 수 있을 것 같습니다.
잘 작동하는것 확인했으니 코드 참고해서 수정해보세요.

```suggestion
const facilityInfo = [
    {
      title: "지하철",
      facility: isSubwayBtnOn,
      alt: "주위에 지하철이 있는지 없는지 확인할 수 있어요",
      img_on: "images/icon/subwayOn1.png",
      img_off: "images/icon/subwayOff.png",
    },
    {
      title: "편의점",
      facility: isStoreBtnOn,
      alt: "주위에 편의점이 있는지 없는지 확인할 수 있어요",
      img_on: "images/icon/storeOn1.png",
      img_off: "images/icon/storeOff.png",
    },
    {
      title: "카페",
      facility: isCafeBtnOn,
      alt: "주위에 카페가 있는지 없는지 확인할 수 있어요",
      img_on: "images/icon/cafeOn1.png",
      img_off: "images/icon/cafeOff.png",
    },
    {
      title: "학교",
      facility: isSchoolBtnOn,
      alt: "주위에 학교가 있는지 없는지 확인할 수 있어요",
      img_on: "images/icon/schoolOn1.png",
      img_off: "images/icon/schoolOff.png",
    },
  ];

  const handleShownIcon = (title) => {
    switch (title) {
      case "학교":
        setSchoolBtnOn(!isSchoolBtnOn);
        break;
      case "카페":
        setCafeBtnOn(!isCafeBtnOn);
        break;
      case "편의점":
        setStoreBtnOn(!isStoreBtnOn);
        break;
      case "지하철":
        setSubwayBtnOn(!isSubwayBtnOn);
        break;
    }
  };

  return (
    <Footer>
      <div className="iconContainer">
        {facilityInfo.map((el) => {
          return (
            <div className="icon" onClick={() => handleShownIcon(el.title)}>
              <img
                alt={el.alt}
                className="Icon"
                src={el.facility ? el.img_on : el.img_off}
              />
              <span>{el.title}</span>
            </div>
          );
        })}
```

2020-12-10 04:21 UTC, claire-euni commented on src/Components/NearBy/Modal/NearbyModal.js
> +  // const [center, setCenter] = useState();
불필요한 주석은 삭제

2020-12-10 04:21 UTC, claire-euni commented on src/Components/NearBy/Modal/NearbyModal.js
> +    }
이 함수들도 반복되므로 컴포넌트처럼 함수만 분리해서 차이가 있는 값만 props로 주고 재활용 가능할것 같습니다. 고민해보세요🙌

2020-12-10 04:39 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +            // className={isBodyShow ? "arrowUp" : "arrowDown"} 이걸 어떻게 props로 내려줄 수 있을까여?
오...이렇게해야하는거군용....
props로 내려주고 구조분해할당해서 이렇게 한다...!
신기하네용 ㅎㅎㅎ

감사합니다!

2020-12-10 04:40 UTC, HocheolJang commented on src/Components/NearBy/Modal/NearbyModal.js
> +  // const [center, setCenter] = useState();
아 이거는 사용할 예정입니다 ! 
주석 풀고 사용하도록 하겠습니당 ㅎㅎㅎ

2020-12-10 04:57 UTC, HocheolJang commented on src/Components/NearBy/Modal/Component/NearbyModalFooter.js
> +          <span>지하철</span>
오 역시........
훌륭하십니당....
한 번 더 덜어낼 수 있는 방법이 있는지도 해보겠습니당

2020-12-10 05:00 UTC, HocheolJang commented on src/Components/NearBy/Modal/Component/NearbyModalFooter.js
> +          <span>지하철</span>
facility info도 mockdata로 덜어내고 import해오는걸로 변경했습니당
감사합니당

2020-12-10 07:18 UTC, HocheolJang commented
준님께서 많이 도와주셔서 우선 리팩토링 1차로 진행했습니다.
코드는 다시 공부해보겠습니다 !
현재 로드뷰도 시도중입니다 ~ 잘 될 지 모르겠지만 일단 계속 시도해보겠스빈당

2020-12-10 07:19 UTC, HocheolJang commented on src/Components/NearBy/Modal/NearbyModal.js
> +    }
네에 ㅎㅎㅎ우선 진행했습니당

2020-12-10 07:19 UTC, HocheolJang commented on src/Components/NearBy/Modal/NearbyModal.js
> +    createSchoolMarkers();
감사합니다

2020-12-10 07:45 UTC, claire-euni commented on src/Components/NearBy/Card/NearbyCard.js
> +    isBodyShow ? "rotate(-270deg)" : "rotate(-90deg)"};
굿!

2020-12-10 07:45 UTC, claire-euni commented on src/Components/NearBy/Modal/Component/NearbyModalMocks.js
> +  {
이렇게 파일 분리하실거면 ModalFooter에서는 배열 지우셔도 될것 같습니다!

2020-12-10 08:02 UTC, merged

2020-12-10 08:30 UTC, HocheolJang commented on src/Components/NearBy/Card/NearbyCard.js
> +    isBodyShow ? "rotate(-270deg)" : "rotate(-90deg)"};
ㅋㅋㅋㅋ잘됩니다 역시 운정님!

2020-12-10 08:31 UTC, HocheolJang commented on src/Components/NearBy/Modal/Component/NearbyModalMocks.js
> +  {
네에 ㅎㅎ 근데 분리해보니까 스테이트값이 안받네요.......
그냥 같이 써야할 것같스빈다