[14기 김동하] feature/filter UI 및 기능 구현
wecode-bootcamp-korea/14-2nd-SHABANG-frontend pull request #4
Opened 2020-12-02 15:30 UTC by dongha1992

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-필터 UI 및 기능 구현했습니다. 

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 필터 UI 및 기능 구현했습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- useState를 이용해서 여러 버튼에서 클릭한 value값을 input에 차례대로 나타나게 해주는데 중복을 방지하고 싶습니다. 일단 제가 해봤는데 중복이 있다면(중복검사 함수) 클릭을 방지하는 함수를 어떻게 할지 모르겠습니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-07 02:16 UTC, dipsiiiiiiiiii commented
안녕하세요 동하님! 질문하신 중복 방지 기능 관련해서 코드를 첨부해주실 수 있나요?

2020-12-07 08:06 UTC, Jun4928 requested changes
동하님 간단한 리뷰 하나 남겨드렸습니다.
혹시 질문하신 사항은 해결하셨나요?

2020-12-07 08:06 UTC, Jun4928 commented on src/Pages/Apartment/Apartment.js
> +  };
다음 코드 스니펫을 이용해서 해당 로직을 리팩토링 해 보세요!
if 문의 분기보다 다음과 같이 객체에 함수를 맵핑 해 주면 보다 더 명확하게 로직을 처리할 수 있습니다.
```js
const setUserSelect = (name, value) => {
  const mapper = {
    type: () => console.log('type', value),
    area: () => console.log('area', value),
    foundation: () => console.log('foundation', value),
    houseHolds: () => console.log('houseHolds', value) 
  }
    
  mapper[name]()
}

const onChangeUserSelectKeyword = (e) => {
  const { name, value } = e.target
  setUserSelect(name, value)
}

onChangeUserSelectKeyword(e)
```

2020-12-07 08:35 UTC, dongha1992 commented
> 안녕하세요 동하님! 질문하신 중복 방지 기능 관련해서 코드를 첨부해주실 수 있나요?

중복 방지는 해결했는데 다음 문제가 생겨 스크린샷으로 첨부했습니다! 준님이 리뷰해주신 것 같은데 확인해보겠습니다. 감사합니다!!

2020-12-07 08:37 UTC, dongha1992 commented on src/Pages/Apartment/Apartment.js
> +  };
아직 해결 되지 않았습니다! 일단 접근은 첫 번째 클릭 인덱스, 두 번째 클릭 인덱스 그 사이를 모두 true(검정색)으로 변환인데  첫 번째, 두 번째 클릭을 했을 때 state에 범위를 어떻게 담을지 고민 중입니다!

2020-12-07 08:58 UTC, Jun4928 commented
간단한 코드 스니펫을 만들어 봤는데, 다음과 같이 하면
state는 startIndex와 endIndex 만 있으면 해결할 수 있지 않을까요?
범위를 다 기억하고 있을 필요가 없습니다. 

```js
const buttons = [
  {
    name: '전체',
    isOn: false,
  },
  {
    name: '10평 이하',
    isOn: false, 
  },
  {
    name: '10평대',
    isOn: false,
    
  },
  {
    name: '20평대',
    isOn: false,
    
  },
  {
    name: '30평대',
    isOn: false,
  },
  {
    name: '60평 이상',
    isOn: false,
  },
]

const setColors = (startIndex, endIndex) => {
  return buttons.map((button, index) => {
    const isSelected = index >= startIndex && index <= endIndex
    
    if (isSelected) return {
      ...button,
      isOn: true
    }
    
    return {
      ...button,
      isOn: false
    }
  })
}


setColors(1, 2)
```

2020-12-09 14:21 UTC, dongha1992 commented on src/Pages/Apartment/Apartment.js
> +  };
수정했습니다!! 객체 안에 함수를 쓸 생각은 태어나서 해본 적이 없어서. 너무 낯설지만 훨씬 보기 좋네요!! 연습해보겠습니다.

2020-12-09 14:21 UTC, dongha1992 commented
> 간단한 코드 스니펫을 만들어 봤는데, 다음과 같이 하면
> state는 startIndex와 endIndex 만 있으면 해결할 수 있지 않을까요?
> 범위를 다 기억하고 있을 필요가 없습니다.
> 
> ```js
> const buttons = [
>   {
>     name: '전체',
>     isOn: false,
>   },
>   {
>     name: '10평 이하',
>     isOn: false, 
>   },
>   {
>     name: '10평대',
>     isOn: false,
>   },
>   {
>     name: '20평대',
>     isOn: false,
>   },
>   {
>     name: '30평대',
>     isOn: false,
>   },
>   {
>     name: '60평 이상',
>     isOn: false,
>   },
> ]
> 
> const setColors = (startIndex, endIndex) => {
>   return buttons.map((button, index) => {
>     const isSelected = index >= startIndex && index <= endIndex
>     
>     if (isSelected) return {
>       ...button,
>       isOn: true
>     }
>     
>     return {
>       ...button,
>       isOn: false
>     }
>   })
> }
> 
> 
> setColors(1, 2)
> ```

죄송합니다... 최선을 다 해보려고 했지만 너무 어렵네요ㅠㅠ......준님의 코드를 이해하는 그 날까지....

2020-12-10 04:59 UTC, dipsiiiiiiiiii reviewed
동하님! 주석만 제거해주시면 머지하겠습니다!

2020-12-10 04:59 UTC, dipsiiiiiiiiii commented on src/Pages/Apartment/components/Map/MapContainer.js
> +  //         ? props.userClickedFilteredData.lat
주석만 제거해주세요!

2020-12-10 05:35 UTC, dongha1992 commented on src/Pages/Apartment/components/Map/MapContainer.js
> +  //         ? props.userClickedFilteredData.lat
제거 했습니다!!

2020-12-10 13:03 UTC, merged