[14기 김동하] 그래프 UI 및 기능 구현
wecode-bootcamp-korea/14-2nd-SHABANG-frontend pull request #6
Opened 2020-12-03 16:25 UTC by dongha1992

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- high chart를 이용해서 그래프를 구현했습니다. 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- high chart를 이용해서 그래프를 구현했습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 목데이터로 그래프를 만들었는데 백엔드에게 받으면 어떻게 될지 걱정이 됩니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-07 08:26 UTC, Jun4928 requested changes
멋진 코드 기대하겠습니다. 동하님 👍

2020-12-07 08:26 UTC, Jun4928 commented on src/Pages/Apartment/components/PriceChart.js
> +        <span><b>${(points[0].y - points[1].y).toFixed(2)} 차이${1}%</span>
- points[0], points[1] 이 순서쌍이긴 하지만 각각이 의미를 갖고 있으므로 변수를 통해 드러내 주는 것이 어떨까요?
- 배열의 구조분해 할당을 사용하면 됩니다.

ex)
```js
const [dealingPrice, leasePrice] = points
```
변수명은 적당한게 안 떠올라서 예시로 넣어봤습니다.
좋은 이름을 붙여주세요

2020-12-07 08:26 UTC, Jun4928 commented on src/Pages/Apartment/components/ProductDetail.js
> +];
호철님께 달아드린 다음 [리뷰](https://github.com/wecode-bootcamp-korea/14-2nd-SHABANG-frontend/pull/3#discussion_r537250000)를 참고해서 상수의 이름을 리팩토링 해주세요.

2020-12-07 08:26 UTC, Jun4928 commented on src/Utils/highchartOptions.js
> +const highchartOptions = {
위 컴포넌트에도 이 옵션이 선언되어 있던데, 
재사용 하기 위함인가요?

2020-12-09 15:59 UTC, dongha1992 commented on src/Utils/highchartOptions.js
> +const highchartOptions = {
아 실수입니다. 삭제하겠습니다!!

2020-12-10 05:08 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +];
data로 빼서 js파일로 import 하려고 했는데 잘 안 되네요.. json으로 빼서 fetch 받아야 하나요?
<img width="475" alt="스크린샷 2020-12-10 오후 2 08 06" src="https://user-images.githubusercontent.com/58624851/101724116-20fe5400-3af1-11eb-8617-d60f11d5d56f.png">

이렇게 해봤습니다!

2020-12-10 05:24 UTC, dongha1992 commented on src/Pages/Apartment/components/PriceChart.js
> +        <span><b>${(points[0].y - points[1].y).toFixed(2)} 차이${1}%</span>
네 확인했습니다!!!

2020-12-10 05:25 UTC, dongha1992 commented
> 멋진 코드 기대하겠습니다. 동하님 👍

시간이 부족해서 디테일에 신경을 못 쓰네요ㅠㅠ리팩토링 때 잘 해볼게요. 세심한 리뷰 감사드립니다!

2020-12-10 05:32 UTC, dongha1992 commented
2020. 12 .10

- push할 땐 아무 문제 없었는데 login에서 컨플릭트가 났다고 하네요 왜 그런 것이죠..?

2020-12-10 07:34 UTC, claire-euni reviewed
동하님 반복되는 함수구문을 하나로 합쳐보면 좋을것 같네요! 리뷰반영해서 리팩 해주세요 :)

2020-12-10 07:34 UTC, claire-euni commented on .eslintcache
> +[{"/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/Apartment/Apartment.js":"1","/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/LogIn/LogIn.js":"
가이드 참고해서 eslinecache 파일 올라오지 않게 해주세요!

2020-12-10 07:34 UTC, claire-euni commented on .eslintcache~78f3f0d... [finished] 그래프 UI 및 기능 구현
> +[{"/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/Apartment/Apartment.js":"1","/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/LogIn/LogIn.js":"
이 파일도 마찬가지!

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/Map/MapContainer.js
> +      console.log(getLevel);
콘솔 삭제!

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/PriceChart.js
> +  }
반복되는 부분 변수로 설정해서 사용하는게 간결할 것 같습니다 

```suggestion
let aptData = tabbedData.trade_apartments_data;

  for (let idx in tabbedData && aptData ) {
    for (let year in tabbedData && aptData[idx]) {
      years.push(year);
      sellingYears.push(Object.values(aptData[idx]));
    }
  }
```

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/PriceChart.js
> +  }
아래 sellingYearsVaues 와 sellingYearsDate, renting도 4개가 동일한 함수 기능을 하는데 하나로 묶어주는게 좋겠네요!
```js

const target = [
{ title: sellingYearsValues, emptyArr:testValue},
{ title: sellingYearsDate, emptyArr: sellingDateForX }, 
...  
]

target.map((el)=> {
     for(let data in el.title) {
    let temp = el.title[data][0];
    let targetArr = el.emptyArr;
        temp.map((element)=> {
             targetArr.push(el);
} 
}
)}


```

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +const yearArray = ['1년', '3년', '5년', '전체'];
변하지 않는 고정적인 전역 변수라면 YEARARRAY라는 식으로 대문자로 작성해주시는게 컨벤션입니다~

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +};
them provider로 잘 묶어주셨는데 productDetail 컴포넌트에서만 쓰이는 속성들인가요?
아니라면 index.js에서 전체로 묶어주시면 됩니다!
![image](https://user-images.githubusercontent.com/61927257/101734478-adb20d80-3b03-11eb-90c7-e94f19c66609.png)

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +  }, [scrollTop]);
* scollTop을 state에서 관리할 필요가 있나요? 말그대로 스크롤마다 숫자가 바뀌면서 setState으로 저장해주는 상태인데 성능면에서 좋지 않을것 같고 불필요해보입니다. 그냥 target.current.scrollTop을 변수에 저장하고 아래와같이 조절해줄 수 있을것 같습니다. 

```js
  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);
```

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +  //     });
사용안하시면 삭제!

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +  const getYearOfData = () => {};
?

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +  };
기능이 동일한 함수입니다 props로 달라지는 인자만 전달해서 조건에 따라서 작동할 수 있게 하나의 함수로 합쳐주세요

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +const ProductTabChange = styled.div``;
속성없다면 굳이 스타일 컴포넌트화로 분리 안해도 되겠습니다~

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductDetail.js
> +  }
```suggestion
 .foundation_date, .floor, .type, .price {
     width: 25%;
 }
```

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductTradeData.js
> +        <GridWrap key={idx}>
key는 고유값으로 주는게 좋습니다. idx로 주면 배열의 요소갯수와 변동사항에 의해서 index도 변하기 때문에 다른 고유값으로 고민해보세요~

2020-12-10 07:34 UTC, claire-euni commented on src/Pages/Apartment/components/ProductTradeData.js
> +`;
이렇게 공통된 속성을 가진 컴포넌트를 하나로 관리해주기 위해서 스타일 컴포넌트를 사용하는거에요~
하나의 컴포넌트로 만들어주세요 🤗

2020-12-10 08:04 UTC, dongha1992 commented on .eslintcache
> +[{"/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/Apartment/Apartment.js":"1","/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/LogIn/LogIn.js":"
네!! 잊었습니다 죄송합니다!!

2020-12-10 08:05 UTC, dongha1992 commented on .eslintcache~78f3f0d... [finished] 그래프 UI 및 기능 구현
> +[{"/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/Apartment/Apartment.js":"1","/Users/donghakim/14-2nd-SHABANG-frontend/14-2nd-SHABANG-frontend/src/Pages/LogIn/LogIn.js":"
요건 그냥 삭제 해도 될까요? git -rm으로 안 잡히네요!

2020-12-10 08:06 UTC, dongha1992 commented on src/Pages/Apartment/components/Map/MapContainer.js
> +      console.log(getLevel);
삭제했습니다!!

2020-12-10 09:29 UTC, dongha1992 commented on src/Pages/Apartment/components/PriceChart.js
> +  }
아 훨씬 보기 좋네요!! 수정했습니다!

2020-12-10 09:31 UTC, dongha1992 commented on src/Pages/Apartment/components/PriceChart.js
> +  }
이것이 인간의 사고로 가능한 코드인가요?

2020-12-10 10:23 UTC, dongha1992 commented on src/Pages/Apartment/components/PriceChart.js
> +  }
했습니다!! 굉장하네요... 생각도 못했어요. 그런데 이해하고 넘어간 것이 아니라 플젝 끝나고 다시 리팩토링 꼭 하겠습니다!!!!!!!! 좋은 코드 감사합니다.

2020-12-10 10:23 UTC, dongha1992 commented on src/Pages/Apartment/components/PriceChart.js
> +  }
제가 예전에 했던 건 주석으로 남겼는데 이건 놔두게 허락해주세요!

2020-12-10 10:24 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +const yearArray = ['1년', '3년', '5년', '전체'];
네 명심하겠습니다!!

2020-12-10 10:24 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +};
저 컴포넌트에만 쓰이는 속성이라 저렇게 했습니다!!

2020-12-10 10:27 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +  //     });
삭제했습니다!!

2020-12-10 10:27 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +  const getYearOfData = () => {};
임포스터 제거 완료..

2020-12-10 10:30 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +  }
확인했습니다!!!

2020-12-10 11:42 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductTradeData.js
> +`;
확인했습니다!!

2020-12-10 11:42 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +const ProductTabChange = styled.div``;
나중에 쓰일 것 같아서 해놨는데 삭제하겠습니다!

2020-12-10 11:43 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +const ProductTabChange = styled.div``;
나중에 서버에서 데이터 받으면 바꿔야 해서 놔뒀는데 일단 내용이 없어서 이대로 뒀습니다! 그대로 둬도 될까요?

2020-12-10 11:48 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductTradeData.js
> +        <GridWrap key={idx}>
아하 여태까지 index값으로 줬는데 서버에서 id를 받으면 id로 교체하겠습니다. 일단 지금은 목데이터 중 절대 겹칠 일이 없는 요소로 key를 해뒀습니다!

2020-12-10 12:21 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +  }, [scrollTop]);
음.. 일단 sticky되는 대상이 window가 아니라  ref로 잡은 div이라 window에 이벤트리스너를 해도 되나요..? setState없이 해보려고 했는데 도무지 안 돼 일단 수정하진 못했습니다!! 제가 서버와 통신이 지금 당장 조금 급한데 일단 서바랑 맞추기만 하고 꼭꼭 수정하겠습니다!!!

2020-12-10 12:24 UTC, dongha1992 commented on src/Pages/Apartment/components/ProductDetail.js
> +  };
원래 서버에서 주는 평수에 따라 달라지는 UI를 표현하기 위해서 이렇게 만들었던 것인데 지금 디테일 데이터 / 그래프 데이터 이렇게 두 데이터를 다르게 받아서 사실 어떻게 수정해야할지 모르겠습니다!! 사실 지금 머리가 잘 안 돌아가서 리팩토링은 발표가 끝나고 주말에 꼭꼭 진행하겠습니다 죄송합니다!

2020-12-11 03:37 UTC, dongha1992 commented
 컨플릭 해결했습니다!!

2020-12-11 04:07 UTC, dongha1992 commented
해결 했습니다ㅣ

2020-12-11 04:21 UTC, merged