[14기 엄문주] NavBar 레이아웃 및 기능 구현 했습니다.
wecode-bootcamp-korea/14-2nd-SHABANG-frontend pull request #7
Opened 2020-12-04 02:18 UTC by eommoonjoo

## 수정 사항 간략한 한줄 요약
- NavBar 레이아웃 작업 및 기능구현
		 
## 수정 사항들 자세한 내용
- NavBar 레이아웃 
- Dropdown 메뉴 구현
- Router에 따른 메뉴 색상 변경 구현

## 기타 질문 및 특이 사항
- 특이사항 없습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-07 08:43 UTC, Jun4928 requested changes
@eommoonjoo 
문주님! 만나서 리팩토링 방향에 대해서 이야기 나누도록 해요

2020-12-07 08:43 UTC, Jun4928 commented on src/Components/NavBar/DropdownAp.js
> +const MenuItems = [
호철님께 달아드린 다음 [리뷰](https://github.com/wecode-bootcamp-korea/14-2nd-SHABANG-frontend/pull/3#discussion_r537250000)를 참고해서 상수명 리팩토링 해주세요.

2020-12-07 08:43 UTC, Jun4928 commented on src/Components/NavBar/DropdownNew.js
> +const MenuItems = [
여기도 마찬가지로 상수명 리팩토링 해주세요!

2020-12-07 08:43 UTC, Jun4928 commented on src/Components/NavBar/DropdownAp.js
> +          {MenuItems.map((item, index) => {
이렇게 배열안에 객체의 Key 값들이 고정되어 있다면 인자로 받을 때 구조분해 할당 하는게 좋습니다. 
무의미한 변수명을 짓지 않아도 되고, 렌더링 하는 요소가 명확해지기 때문입니다.

```js
MENU_ITEMS.map(({cName, path, title}, index) => { ... })
```

2020-12-07 08:43 UTC, Jun4928 commented on src/Components/NavBar/DropdownNew.js
> +        <ul onClick={handleClick}>
handleClick 에 새 함수 만들지 않고
태그 안에서 함수를 맵핑해 주면 되지 않을까요?

```js
<ul onClick={() => setClick(!click}>
```

2020-12-07 08:43 UTC, Jun4928 commented on src/Components/NavBar/DropdownNew.js
> +              </li>
여기도 위와 동일한 리뷰 참고하셔서 구조분해할당 리팩토링 해주세요!

2020-12-07 11:33 UTC, Jun4928 commented
```js
const DropDown = (props) => {
  const { type, menu } = props
  
  return (
    <>
    <DropDownMenu type={type}>
    {menu.map(({title, path}) => {
      // ...
    })}
    </DropDownMenu>
    </>
  )
}

// <DropDown type={small 또는 big} menu={menu}/>

const props = {
  type: 'small',
  menu: [
    {
      title: 'abc',
      path: '/asdf'
    },
    {
      title: 'abc2',
      path: '/asdf2'
    },
  ]
}

// 부모 컴포넌트 Nav 에서 DropDown을 렌더링 할 때 props로 type 과 렌더링할 데이터를
// 내려주세요.
DropDown(props)

const DropDownMenu = styled.div`
  height: ${props => props.type === 'small' ? '120' : '200'}px
  width: ${props => props.type === 'small' ? '80' : '100'}px
`
```

2020-12-07 11:34 UTC, Jun4928 commented
dropdown true, false 를 위해서 모든 스테이트를 선언하는게 아니라
다음과 같이 배열을 이용해 주세요
```js
const [dropdowns, setDropDowns] = useState([...Array(5)].fill(false))
```

2020-12-10 14:03 UTC, dipsiiiiiiiiii reviewed
이 파일 두 개만 수정해주세요! 컨플릭트가 덜 해결 돼있네요!

2020-12-10 14:03 UTC, dipsiiiiiiiiii commented on public/data/OneRoom.json
> +<<<<<<< HEAD
여기 아직 수정이 덜 됐습니다!

2020-12-10 14:03 UTC, dipsiiiiiiiiii commented on public/index.html
> +<<<<<<< HEAD
여기도!

2020-12-10 14:12 UTC, eommoonjoo commented on public/data/OneRoom.json
> +<<<<<<< HEAD
넵, 해결 하겠습니다.

2020-12-10 14:17 UTC, eommoonjoo commented on public/data/OneRoom.json
> +<<<<<<< HEAD
수정 했습니다, 관희님

2020-12-10 14:17 UTC, eommoonjoo commented on public/index.html
> +<<<<<<< HEAD
수정했습니다, 관희님.

2020-12-10 15:46 UTC, merged